title: Blog cá nhân - Tiền Minh Vy
email: admin@tienminhvy.com
description: > # this means to ignore newlines until "baseurl:"
  Là một lập trình viên có nhiều kinh nghiệm với mã nguồn PHP
  Nhận dự án Freelance. Ưa chuộng mã nguồn mở
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Tiền Minh Vy # add your name
author-pic: author.png
about-author: Tôi là Tiền Minh Vy. Là một lập trình viên có nhiều kinh nghiệm với mã nguồn PHP. Nhận dự án Freelance nếu bạn cần. Mình rất ưa chuộng mã nguồn mở

# Contact links
email: tienminhvydev@gmail.com # Add your Email address
phone: # Add your Phone number
website: tienminhvy.com # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: tienminhvy # Add your Github handle
twitter: '@tienminhvy' # Add your Twitter handle
facebook: tienminhvydev # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
